version: '3.3'

services:

  redis:
    image: redis:alpine
    hostname: tag-redis
    ports:
      - "6379"
    networks:
        - backend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  db:
    image: postgres:10-alpine
    container_name: tag-db
    hostname: tag-db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

networks:
  backend:

volumes:
  db_data: